Algoritmo "SomarDoisValores"
// Disciplina   : [Lógica de Programação]
// Professor   :
// Descrição   :
// Autor(a)    :
// Data atual  : 12/12/2019
Var
n1, n2, Res: inteiro


Função Soma(a, b : inteiro): inteiro
var
   S: inteiro
Inicio
       s <- a + b
       Retorne S
       //ou
       //Retorne a + b
Fimfuncao


Inicio
      n1 <- 6
      n2 <- 4
      Res <- Soma(n1, n2)
      Escreval("A soma entre ", n1, " e", n2, " = ", Res)
Fimalgoritmo