Algoritmo "OperaRelaLog"
// Disciplina   : Algoritimo
// Professor   :
// Descrição   : Operadores logicos e relacioanais
// Autor(a)    :
// Data atual  : 18/11/2019
Var
  A, B, C: inteiro


Inicio
    A <- 2
    B <- 3
    C <- 4
    Escreval (A>B)
    Escreval (A<B)
    Escreval (A>C)
    Escreval (A<C)
    Escreval (C>B)
    Escreval (C<B)
    verdadeiro ou falso
    Escreval((A=C) ou (B<A))

Fimalgoritmo