Algoritmo "creuza01"
// Disciplina   : [Lógica de Programação]
// Professor   :
// Descrição   : Ajudando a Creuza
// Autor(a)    :
// Data atual  : 25/11/2019
Var

  ano_atual, ano_nasc, idade: inteiro


Inicio
      Escreva("Em que ano estamos? ")
      leia(ano_atual)
      Escreva("Em que ano eu nasci? ")
      leia(ano_nasc)
      idade <- ano_atual - ano_nasc
      Escreval("A sua idade é: ", idade)
 


Fimalgoritmo