Algoritmo "sOMANDONUMEROS"
 //aula de algoritimos - aula 3
Var
nome:caractere
n1: inteiro
n2: inteiro
soma: inteiro

Inicio

Escreva("Oi! Por favor digite seu nome. R_: ")
                 leia (nome)
Escreval("Olá ", nome, " muito prazer!")
Escreval("Digite um numero. R_: ")
                 leia (n1)
Escreval("Digite outro numero. R_: ")
                 leia (n2)
soma <- n1 + n2
Escreval("A soma de ", n1, " e ", n2, " será igual a: ", soma)

Fimalgoritmo