Algoritmo "conteate..."
// Disciplina   : [Lógica de Programação]
// Professor   :
// Descrição   :
// Autor(a)    :
// Data atual  : 02/12/2019
Var

    valor, salto, cont: inteiro

Inicio
      cont <- 0
      Escreva("Quer contar até quanto?: ")
      leia(valor)
      Escreva("Quantos saltos?: ")
      leia(salto)
      Enquanto (cont <= valor) faca
                  Escreval(cont)
                  cont <- cont + salto
      FimEnquanto
      Escreva("Terminei de contar")
Fimalgoritmo